spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: order_group, payment_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.srv.microservices.notification_service.kafka.OrderConfirmation,paymentConfirmation:com.srv.microservices.notification_service.kafka.PaymentConfirmation

  mail:
    host: localhost
    port: 1025
    username: root
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port:
    8040